# This is a basic workflow to help you get started with Actions

name: Run Codes

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Get an actor
      - name: Get an actor
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: echo "$GITHUB_ACTOR"

      # Run a python code
      - name: Run a python code
        run: python pythoning.py $GITHUB_ACTOR

      # Run a ruby code
      - name: Run a a ruby code
        run: ruby rubying.rb
